### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by csherland** [luster/tawfDereverb#1]
I don't hear a difference.

**Comment by luster** [comment]
train those ears, pardner

**Comment by csherland** [comment]
My mistake. Seems to be that my volume was too high. Probably the source of the apparent distortion.

**Comment by luster** [comment]
Still doesn't work

**Comment by luster** [comment]
@csherland still accepting PRs bud

**Comment by csherland** [comment]
Not an issue

**Comment by luster** [comment]
crackin this wide open
